image: golang:1.16

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - go test ./...

deployJob:
  image: docker:19.03.12
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - docker pull golang:1.16-alpine
    - docker pull alpine:3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker logout
    - docker rmi $IMAGE_TAG
